import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { RouteLoader } from "@/components/UI/Loaders";

export const metadata: Metadata = {
  title: "WHIZMSG",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <ToastContainer />
        <RouteLoader />
        {children}
      </body>
    </html>
  );
}
